#@ load("@ytt:data", "data")

apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
- image: kapp-controller
  path: .
  #@ if/end not data.values.image_cache:
  docker:
    build:
      #! Always rebuild image
      pull: true
      noCache: false
      #! pass kapp_controller_version into Dockerfile.
      rawOptions:
        - #@ "--build-arg=KCTRL_VER="+data.values.kapp_controller_version
        #@ if/end data.values.platform != "":
        - #@ "--platform="+data.values.platform

#@ if/end data.values.push_images:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
destinations:
- image: kapp-controller
  newImage: #@ data.values.image_repo
  tag: [latest, namespaced]